/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatchLettersRouteImport } from './routes/match-letters'
import { Route as DayNightRouteImport } from './routes/day-night'
import { Route as IndexRouteImport } from './routes/index'

const MatchLettersRoute = MatchLettersRouteImport.update({
  id: '/match-letters',
  path: '/match-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const DayNightRoute = DayNightRouteImport.update({
  id: '/day-night',
  path: '/day-night',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day-night': typeof DayNightRoute
  '/match-letters': typeof MatchLettersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day-night': typeof DayNightRoute
  '/match-letters': typeof MatchLettersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/day-night': typeof DayNightRoute
  '/match-letters': typeof MatchLettersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day-night' | '/match-letters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/day-night' | '/match-letters'
  id: '__root__' | '/' | '/day-night' | '/match-letters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DayNightRoute: typeof DayNightRoute
  MatchLettersRoute: typeof MatchLettersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/match-letters': {
      id: '/match-letters'
      path: '/match-letters'
      fullPath: '/match-letters'
      preLoaderRoute: typeof MatchLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-night': {
      id: '/day-night'
      path: '/day-night'
      fullPath: '/day-night'
      preLoaderRoute: typeof DayNightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DayNightRoute: DayNightRoute,
  MatchLettersRoute: MatchLettersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
